/* Tests for the demo data builder (js/demo.js). The plan itself is generated in
   storage.seedDemo() by the real generator (browser-tested). */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildDemo, demoHealthSeries, demoCycle, completeDemoUnits, planPeriodSessions } from '../js/demo.js';
import { isoDow } from '../js/ui.js';
import { trainingLoad } from '../js/load.js';
import { eligibilityFor } from '../js/eligibility.js';
import { SUGGESTED_MEALS } from '../js/nutrition.js';

const TODAY = '2026-06-15';

test('buildDemo: admin gets profile, location, goals, race, lots of history + further areas', () => {
  const d = buildDemo(TODAY);
  assert.ok(d.profile.heightCm && d.profile.targetWeightKg, 'profile values set');
  assert.ok(d.profile.birthYear, 'birth year for the calorie balance');
  assert.ok(d.settings && d.settings.location && d.settings.location.lat != null, 'location set for the weather');
  assert.ok(d.settings.healthGoals && d.settings.healthGoals.length >= 2, 'health goals for the demo');
  assert.equal(d.settings.modules && d.settings.modules.cycle, true, 'cycle module enabled');
  const usage = d.settings.exerciseUsage || {};
  assert.ok(Object.keys(usage).length >= 8, 'exercise usage counters preset (v3.11.0)');
  assert.ok((usage.child_pose || 0) > 0 || (usage.superman || 0) > 0, 'new exercises with usage too');
  assert.equal(d.self.events.length, 1);
  assert.equal(d.self.events[0].kind, 'race');
  assert.ok(d.self.events[0].location, 'race has a location');
  assert.ok(d.self.sessions.length >= 28, `plenty of training history (was ${d.self.sessions.length})`);
  assert.ok(d.self.sessions.every((s) => s.status === 'erledigt'), 'history is completed');
  assert.ok(new Set(d.self.sessions.map((s) => s.type)).size >= 4, 'different kinds of training');
  assert.ok(d.self.health.length >= 6, 'weight/pulse series');
  assert.ok(d.self.nutrition.length >= 4, 'planned dishes (weekly plan)');
  assert.ok(d.self.nutrition.every((m) => m.plannedServings > 0 && Array.isArray(m.ingredients) && m.ingredients.length), 'dishes scheduled incl. ingredients');
  assert.ok(d.pantry.length >= 4, 'shared family pantry filled');
  assert.ok(d.pantry.every((p) => p.name && p.unit && p.amount > 0), 'pantry entries complete');
  assert.ok(d.self.diary.length >= 2 && d.self.diary.filter((x) => !x._kind).every((x) => x.kcal > 0), 'eaten today (calorie balance; day markers without kcal)');
  assert.ok(d.self.checklist.length >= 4, 'checklist (routines + appointments)');
  assert.ok(d.self.checklist.some((c) => c.dueDate), 'at least one appointment with a date');
  assert.equal(d.self.plans, undefined, 'plan is generated by seedDemo, not by the builder');
});

test('buildDemo: 10 demo members (11-person scenario) with full data richness', () => {
  const d = buildDemo(TODAY);
  assert.equal(d.members.length, 10);
  d.members.forEach((m) => {
    assert.ok(m.name && ['user', 'admin'].includes(m.role));
    assert.ok(Array.isArray(m.data.sessions) && m.data.sessions.length >= 8, 'plenty of runs');
    assert.ok(Array.isArray(m.data.health) && m.data.health.length >= 10, 'long values series');
    assert.ok(Array.isArray(m.data.events));
    assert.ok(m.profile && m.profile.sex && m.profile.settings, 'member has a complete profile');
  });
  assert.equal(d.members.filter((m) => m.role === 'admin').length, 3, 'together with the admin person 4 admins');
  assert.ok(d.members.some((m) => (m.data.nutrition || []).some((x) => x.plannedServings > 0)), 'members plan dishes (shared weekly plan)');
  assert.ok(d.members.some((m) => m.name === 'Horst') && d.members.some((m) => m.name === 'Henriette'));
});

test('buildDemo: a child and youth profile (Jonas, 12) without a target weight', () => {
  const d = buildDemo(TODAY);
  const kid = d.members.find((m) => m.name === 'Jonas');
  assert.ok(kid, 'minor demo member present');
  const elig = eligibilityFor({ profile: kid.profile, settings: kid.profile.settings, today: TODAY });
  assert.equal(elig.minor, true);
  assert.equal(elig.noWeightGoals, true);
  assert.equal(kid.profile.targetWeightKg, null);
  assert.ok(kid.profile.heightCm < 170, 'child-appropriate height');
  // Growth: the weight rises slightly instead of dropping.
  const w = kid.data.health.filter((h) => h.weight != null);
  assert.ok(w.at(-1).weight >= w[0].weight - 0.5);
  // All adults remain adults.
  assert.equal(d.members.filter((m) => eligibilityFor({ profile: m.profile, settings: m.profile.settings, today: TODAY }).minor).length, 1);
});

test('buildDemo: diary days confirmed, dishes as in the recipe catalogue', () => {
  const d = buildDemo(TODAY);
  const days = new Set(d.self.diary.filter((x) => !x._kind).map((x) => x.date));
  const marked = d.self.diary.filter((x) => x._kind === 'day' && x.complete);
  assert.equal(marked.length, days.size - 1, 'every past day confirmed, today still open');
  assert.ok(!marked.some((x) => x.date === TODAY));
  assert.ok(d.self.diary.filter((x) => x._kind).every((x) => x.kcal == null), 'markers do not count as a meal');
  for (const m of d.self.nutrition) {
    const cat = SUGGESTED_MEALS.find((s) => s.title === m.title);
    if (!cat) continue;
    assert.equal(m.kcal, cat.kcal, `${m.title}: kcal as in the catalogue`);
    assert.equal(m.protein, cat.protein, `${m.title}: protein as in the catalogue`);
  }
  const oats = d.self.diary.find((x) => x.date === TODAY && x.title === 'Overnight Oats mit Beeren');
  assert.ok(Math.abs(oats.kcal - SUGGESTED_MEALS.find((s) => s.title === oats.title).kcal) <= 520 * 0.08, 'diary close to the catalogue value');
});

test('buildDemo: 3 teams – Henriette in 2 teams, Horst in none', () => {
  const d = buildDemo(TODAY);
  assert.equal(d.teams.length, 3);
  const inTeams = (name) => d.teams.filter((t) => t.memberNames.includes(name)).length;
  assert.equal(inTeams('Henriette'), 2, 'Henriette in two teams (multiple membership)');
  assert.equal(inTeams('Horst'), 0, 'Horst stays without a team');
  assert.ok(d.teams.some((t) => t.memberNames.includes('__self__')), 'admin (Nora) is in a team');
  assert.ok(d.teams.every((t) => t.name && t.memberNames.length >= 3));
});

test('buildDemo: the admin AND every woman have cycle data – each their own, unique (private)', () => {
  const d = buildDemo(TODAY);
  assert.ok(Array.isArray(d.self.cycle) && d.self.cycle.length >= 1, 'admin (Nora) has own cycle data');
  const women = d.members.filter((m) => m.sex === 'w');
  const men = d.members.filter((m) => m.sex === 'm');
  assert.ok(women.length >= 4, 'several female members');
  women.forEach((m) => assert.ok(Array.isArray(m.data.cycle) && m.data.cycle.length >= 1, `${m.name} (w) has own cycle data`));
  men.forEach((m) => assert.equal(m.data.cycle, undefined, `${m.name} (m) has NO cycle data`));
  // IDs globally unique (no collision self ↔ members).
  const allCycleIds = [...d.self.cycle, ...women.flatMap((m) => m.data.cycle)].map((c) => c.id);
  assert.equal(new Set(allCycleIds).size, allCycleIds.length, 'cycle IDs unique');
});

test('buildDemo: all members have complete master data (profile + settings)', () => {
  const d = buildDemo(TODAY);
  d.members.forEach((m) => {
    const p = m.profile;
    assert.ok(p && p.heightCm && p.weightKg && p.birthYear && p.sex, `${m.name}: profile basics`);
    assert.ok(p.maxHr && p.restHr && Array.isArray(p.hrZones) && p.hrZones.length === 5, `${m.name}: HR zones`);
    assert.ok(p.paceZones && p.paceZones.threshold, `${m.name}: pace zones`);
    assert.ok(p.settings && p.settings.location && p.settings.location.lat != null, `${m.name}: location`);
    assert.equal(p.settings.modules.cycle, m.sex === 'w', `${m.name}: cycle module = female`);
  });
});

test('buildDemo: sessions in the past, date relative to today', () => {
  const d = buildDemo(TODAY);
  assert.ok(d.self.sessions.some((s) => s.date < TODAY), 'past trainings present');
  assert.ok(d.self.sessions.every((s) => /^\d{4}-\d{2}-\d{2}$/.test(s.date)));
});

test('demoHealthSeries: long series with all body/fitness values + realistic trends', () => {
  const h = demoHealthSeries(TODAY);
  assert.ok(h.length >= 30, `long series (was ${h.length})`);
  const last = h.at(-1);
  ['weight', 'bodyFat', 'muscleMass', 'visceralFat', 'restingHr', 'hrv', 'sleepHours', 'energy', 'mood'].forEach((k) =>
    assert.ok(last[k] != null, `metric ${k} present`));
  assert.ok(h.some((x) => x.vo2max != null), 'VO2max at least partly measured');
  assert.ok(h[0].weight > last.weight, 'weight falls over time');
  assert.ok(h[0].hrv < last.hrv, 'HRV rises over time');
  for (let i = 1; i < h.length; i++) assert.ok(h[i - 1].date < h[i].date, 'sorted chronologically');
  assert.deepEqual(demoHealthSeries(TODAY), demoHealthSeries(TODAY), 'deterministic');
});

test('buildDemo: events use valid distance keys (not labels) – otherwise saving crashes', () => {
  const d = buildDemo(TODAY);
  const VALID = ['5k', '10k', 'HM', 'M', 'tri-sprint', 'tri-olympic', 'hyrox', 'custom'];
  assert.ok(VALID.includes(d.self.events[0].distanceType), `admin event: ${d.self.events[0].distanceType}`);
  d.members.forEach((m) => (m.data.events || []).forEach((e) => {
    if (e.kind === 'race') assert.ok(VALID.includes(e.distanceType), `member event: ${e.distanceType}`);
  }));
});

test('demoCycle: several cycles ~every 28 days, chronological', () => {
  const c = demoCycle(TODAY);
  assert.ok(c.length >= 4, 'several cycles');
  assert.ok(c.every((x) => x.startDate && x.periodLength > 0));
  for (let i = 1; i < c.length; i++) assert.ok(c[i - 1].startDate < c[i].startDate, 'chronological');
});

test('buildDemo: every category has demo data (incl. shopping list & zones)', () => {
  const d = buildDemo(TODAY);
  ['events', 'sessions', 'health', 'nutrition', 'diary', 'cycle', 'checklist', 'shopping'].forEach((area) =>
    assert.ok(Array.isArray(d.self[area]) && d.self[area].length > 0, `category ${area} filled`));
  assert.ok(d.self.shopping.every((s) => s.name && s.qty), 'shopping list complete');
  assert.ok(d.profile.paceZones && d.profile.hrZones, 'training ranges (pace/HR zones) in the profile');
});

test('TRAIN-46: demo with club football – with duration and effort in the load', () => {
  const d = buildDemo(TODAY);
  const fb = d.self.sessions.filter((s) => s.type === 'cross_football');
  assert.ok(fb.length >= 16, `Mon/Wed over 9 weeks, were ${fb.length}`);
  assert.ok(fb.every((s) => s.durationSec === 5400 && s.rpe === 7 && s.date < TODAY));
  assert.ok(fb.every((s) => [1, 3].includes(isoDow(s.date))), 'only Mondays and Wednesdays');
  const load7 = trainingLoad(d.self.sessions, TODAY, 7);
  const noFb = trainingLoad(d.self.sessions.filter((s) => s.type !== 'cross_football'), TODAY, 7);
  assert.ok(load7 > noFb, 'football counts toward the load');
});

test('Demo: the old running routine ends in the plan period – football and extra sessions remain', () => {
  const d = buildDemo(TODAY);
  const start = '2026-06-01';
  const kept = planPeriodSessions(d.self.sessions, start, TODAY);
  const inPeriod = kept.filter((s) => s.date >= start && s.date < TODAY);
  assert.ok(inPeriod.length > 0);
  assert.ok(inPeriod.every((s) => s.type === 'cross_football' || s.extra), 'only football and explicitly additional sessions');
  assert.equal(inPeriod.filter((s) => s.extra).length, 2);
  assert.ok(kept.some((s) => s.date < start && s.type === 'long'), 'history before it remains');
});

test('TRAIN-46: every past completed plan unit has a training (football too)', () => {
  const units = [
    { id: 'fb', date: '2026-06-08', type: 'cross_football', title: 'Fußballtraining', fixed: true, intensity: 'normal', targetDurationMin: 90, status: 'erledigt' },
    { id: 'm', date: '2026-06-07', type: 'match', title: 'Fußballspiel', fixed: true, targetDurationMin: 120, status: 'erledigt' },
    { id: 'e', date: '2026-06-09', type: 'easy', title: 'Lockerer Dauerlauf', targetDistanceKm: 8, targetPaceSecPerKm: 350, targetPaceMaxSecPerKm: 370, status: 'erledigt' },
    { id: 'r', date: '2026-06-10', type: 'rest', status: 'erledigt' },
    { id: 'x', date: '2026-06-11', type: 'easy', status: 'erledigt', executedSessionId: 'schon' },
    { id: 'f', date: '2026-06-20', type: 'long', status: 'geplant' },
  ];
  const { units: us, sessions } = completeDemoUnits(units, [], TODAY, 'e1');
  const byUnit = new Map(sessions.map((s) => [s.plannedId, s]));
  assert.equal(byUnit.get('fb').durationSec, 90 * 60);
  assert.equal(byUnit.get('fb').rpe, 7);
  assert.equal(byUnit.get('m').rpe, 8);
  assert.equal(byUnit.get('e').distanceKm, 8);
  assert.equal(byUnit.get('e').paceSecPerKm, 360);
  assert.ok(!byUnit.has('r') && !byUnit.has('x') && !byUnit.has('f'), 'rest day, already linked and future units remain');
  assert.ok(us.filter((u) => ['fb', 'm', 'e'].includes(u.id)).every((u) => u.executedSessionId));
});

test('UI-31: demo members show no internal abbreviations in visible names', async () => {
  const { demoMemberData } = await import('../js/demo.js');
  const d = demoMemberData('dm7', '2026-09-29', { level: 'high', raceOffset: 40 });
  const visible = [...(d.events || []).map((e) => e.name), ...(d.nutrition || []).map((n) => n.title)];
  assert.ok(visible.length > 0);
  assert.ok(visible.every((t) => !t.includes('dm7')), visible.join(' | '));
});

test('v3.21.0: demo shows route, strength sets and the trainer view', async () => {
  const { demoRoute, DEMO_STRENGTH_IDS } = await import('../js/demo.js');
  const { decodePolyline, haversineSum } = await import('../js/gpx.js');
  const { teamLoad } = await import('../js/teamstats.js');
  // Route: length matches the session, ascent below the hill threshold of the form estimate.
  const r = demoRoute(17);
  const pts = decodePolyline(r.route.poly);
  assert.ok(pts.length >= 50 && pts.length <= 150, `${pts.length} points`);
  assert.ok(Math.abs(haversineSum(pts) / 1000 - 17) < 0.5);
  assert.equal(r.route.ele.length, 60);
  assert.ok(r.ascentM > 0 && r.ascentM < 5 * 17, `${r.ascentM} m of ascent`);

  const units = [
    { id: 'k1', date: '2026-06-02', type: 'strength', title: 'Kraft', targetDurationMin: 40, status: 'erledigt' },
    { id: 'k2', date: '2026-06-09', type: 'strength', title: 'Kraft', targetDurationMin: 40, status: 'erledigt' },
    { id: 'k3', date: '2026-06-16', type: 'strength', title: 'Kraft', targetDurationMin: 40, status: 'geplant' },
    { id: 'l1', date: '2026-06-06', type: 'long', title: 'Long Run', targetDistanceKm: 14, status: 'erledigt' },
    { id: 'l2', date: '2026-06-13', type: 'long', title: 'Long Run', targetDistanceKm: 16, status: 'erledigt' },
  ];
  const before = JSON.stringify(units);
  const { units: us, sessions } = completeDemoUnits(units, [], TODAY, 'e1');
  assert.equal(JSON.stringify(units), before, 'input stays unchanged');
  assert.ok(us.filter((u) => u.type === 'strength').every((u) => u.exerciseIds.join() === DEMO_STRENGTH_IDS.join()), 'the future strength session too');
  const k = sessions.filter((s) => s.type === 'strength').sort((a, b) => a.date.localeCompare(b.date));
  assert.equal(k.length, 2);
  const squat = (s) => s.strengthSets.find((x) => x.exerciseId === 'squat').sets[0].kg;
  assert.ok(squat(k[1]) > squat(k[0]), 'the weight rises');
  const longs = sessions.filter((s) => s.type === 'long').sort((a, b) => a.date.localeCompare(b.date));
  assert.ok(!longs[0].route && longs[1].route && longs[1].ascentM > 0, 'only the most recent long run has a route');

  // Trainer view: some adults share, the child never; the map has rows.
  const d = buildDemo(TODAY);
  const sharing = d.members.filter((m) => m.profile.settings.shareLoad === true);
  assert.ok(sharing.length >= 2);
  assert.ok(d.members.filter((m) => m.name === 'Jonas').every((m) => m.profile.settings.shareLoad === false));
  const rows = teamLoad(d.members.map((m) => ({ id: m.name, name: m.name, shareLoad: m.profile.settings.shareLoad, maxHr: m.profile.maxHr, sessions: m.data.sessions, health: m.data.health })), TODAY);
  assert.equal(rows.length, sharing.length);
});
